#!/bin/bash
#-------------------
# Personnal Aliases
#-------------------

# -> Prevents accidentally clobbering files.
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias mkdir='mkdir -p'

alias h='history'
alias j='jobs -l'
alias ..='cd ..'
alias path='echo -e ${PATH//:/\\n}'
#alias print='/usr/bin/lp -o nobanner -d $LPDEST'   # Assumes LPDEST is defined
#alias pjet='enscript -h -G -fCourier9 -d $LPDEST'  # Pretty-print using enscript
#alias background='xv -root -quit -max -rmode 5'    # Put a picture in the background
alias du='du -kh'
alias df='df -kTh'
alias quota='quota -s'
alias a2ps='a2ps -M Letter '

# The 'ls' family (this assumes you use the GNU ls)
alias ll='ls -l'               # show hidden files
alias la='ls -Al'               # show hidden files
alias ls='ls -hF --color=auto' # add colors for filetype recognition
alias lx='ls -lXB'              # sort by extension
alias lk='ls -lSr'              # sort by size
alias lc='ls -lcr' # sort by change time
alias lu='ls -lur' # sort by access time
alias lr='ls -lR'               # recursive ls
alias lt='ls -ltr'              # sort by date
alias lm='ls -al |more'         # pipe through 'more'
alias tree='tree -Csu' # nice alternative to 'ls'

alias grep='grep --color=auto'

# defaults
alias more='less'
alias vi=vim
alias aptu="sudo aptitude update"
alias apti="sudo aptitude install"
alias apts="aptitude search"
alias sane='stty sane'

# ruby
alias be="bundle exec"
alias ber="bundle exec rake"
alias berdm="bundle exec rake db:migrate"
alias berdr="bundle exec rake db:rollback"
alias bec="bundle exec cap"
alias zs="zeus rspec"
alias zr="zeus rake"

# intoximeters

alias intoxlogin='http localhost:3000/api/session username=admin password=password --session admin'
