#!/bin/bash

pathmunge ${HOME}/pcr_pipeline/bin

export PERL5LIB=$HOME/bioperl:$HOME/annotation_pipeline/lib:$PERL5LIB
#export RUBYLIB=$HOME/usr/lib/:/usr/lib/ruby/site_ruby/1.8/
#export GEM_HOME=$HOME/usr/lib/ruby/gems
#export GEM_PATH=$HOME/usr/lib/ruby/gems:/var/lib/gems/1.8/

export JAVA_HOME="/usr/lib/jvm/java-6-sun"
export M2_HOME="/usr/share/maven2/"

export GRAILS_HOME=$HOME/code/grails-core
pathmunge ${GRAILS_HOME}/bin

#export JRUBY_HOME=/opt/jruby
#pathmunge ${JRUBY_HOME}/bin

