#!/bin/bash

alias apt-install="sudo apt-get install"

alias forward-mysql="ssh -L 9306:mysql.mblab.wustl.edu:3306 zest"

if [ -d ${HOME}/pcr_pipeline/bin ]; then
   pathmunge ${HOME}/pcr_pipeline/bin
fi

pathmunge /var/lib/gems/1.8/bin

export PERL5LIB=${HOME}/bioperl:${HOME}/annotation_pipeline/lib:${PERL5LIB}
#export RUBYLIB=$HOME/usr/lib/:/usr/lib/ruby/site_ruby/1.8/
export GEM_HOME=$HOME/usr/lib/ruby/gems
export GEM_PATH=$HOME/usr/lib/ruby/gems:/var/lib/gems/1.8/

alias fmvn="mvn -Dmaven.test.skip=true"

export JAVA_HOME="/usr/lib/jvm/java-6-sun"
export M2_HOME="/usr/share/maven2/"

export GRAILS_HOME=${HOME}/code/grails-core
if [ -d ${GRAILS_HOME} ]; then
    pathmunge ${GRAILS_HOME}/bin
fi
