#!/bin/bash

# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]]; then
    export PATH=$HOME/usr/bin:$PATH
    # Shell is non-interactive.  Be done now
    return
fi

if [[ -e /etc/bashrc ]]; then
    . /etc/bashrc
fi

source $HOME/.site-config
source $DOTC_DIR/aliases
source $DOTC_DIR/color-bash

pathmunge () {
    if ! echo $PATH | /bin/egrep -q "(^|:)$1($|:)" && test -d $1; then
        if [ "$2" = "after" ] ; then
            PATH=$PATH:$1
        else
            PATH=$1:$PATH
        fi
    fi
}

ediff () {
    if test -d $1; then
        emacsclient -c --eval "(ediff-directories \"$1\" \"$2\")"
    else
        emacsclient -c --eval "(ediff-files \"$1\" \"$2\")"
    fi
}

#PS1='\[\033[01;32m\]\u@\h \[\033[01;34m\]\w \$ \[\033[00m\]'
export PS1="\[$red\][\! \u@\h \w]$\[$NC\] "

# tailoring 'less'
export PAGER=less
export LESSCHARSET='utf-8'
#export LESSCHARSET='latin1'

#export LESS='-i -M -F -R -w'
if [ -f /usr/bin/src-hilite-lesspipe.sh ]; then
    export LESSOPEN="| /usr/bin/src-hilite-lesspipe.sh %s"
    export LESS=' -R '
elif [ -f /usr/share/source-highlight/src-hilite-lesspipe.sh ]; then
    export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
    export LESS=' -R '
else
    export LESS=' -M -R ' # Less stuff
fi
#LESSEDIT="%E ?lt+%lt. %f"

export HISTFILE=$HOME/.bashist/`date +%Y-%m-%d_%R`.$$.`hostname`
touch $HISTFILE && chmod 600 $HISTFILE

export PROMPT_COMMAND='history -w' #write to history whenever the prompt is displayed
export HISTSIZE=1000 # Long history
export HISTFILESIZE=10000 # Size of historyfile
export HISTCONTROL="ignoreboth" # Ignore duplicates
export HISTIGNORE="&:ls:ll:dir:la:[bf]g:exit"
export HISTTIMEFORMAT='%F_%T '

#pathmunge /var/lib/gems/1.8/bin
#pathmunge ${HOME}/.gem/ruby/1.8/bin
pathmunge ${HOME}/usr/bin

export CLASSPATH=.
export CPPFLAGS=-I$HOME/usr/include
export CFLAGS=$CPPFLAGS
if [[ -z $LD_LIBRARY_PATH ]]; then
    export LD_LIBRARY_PATH=$HOME/usr/lib
else
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/usr/lib
fi
export LDFLAGS=-L$HOME/usr/lib

export HOSTFILE=$DOTC_DIR/hosts

export OUTPUT_OPTION=""
export EDITOR=emacsclient

set -o emacs
shopt -s extglob cdspell checkwinsize cmdhist histverify hostcomplete >& /dev/null

if [[ -f /etc/bash_completion ]]; then
    . /etc/bash_completion
fi

if [ -f $DOTC_DIR/bashrc-$DOTC_NAME ]; then
    . $DOTC_DIR/bashrc-$DOTC_NAME
fi

if which keychain > /dev/null; then
    keychain --ignore-missing -Q -q id_rsa adjudica
    source ~/.keychain/$HOSTNAME-sh
fi


# gets called every time need to fix for once it's set
#if [[! -f ~/.xmodmap ]]; then
#    xmodmap $DOTC_DIR/xmodmap
#fi

unset pathmunge
export PATH
xset b off > /dev/null 2>&1

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
