#!/bin/bash

# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]]; then
    export PATH=$HOME/usr/bin:$PATH
    # Shell is non-interactive.  Be done now
    return
fi

source $HOME/.site-config
source $DOTC_DIR/aliases
source $DOTC_DIR/color-bash
eval `dircolors $DOTC_DIR/dircolors.solarized.ansi-universal`

pathmunge () {
    if ! echo $PATH | /bin/egrep -q "(^|:)$1($|:)" && test -d $1; then
        if [ "$2" = "after" ] ; then
            PATH=$PATH:$1
        else
            PATH=$1:$PATH
        fi
    fi
}

ediff () {
    if test -d $1; then
        emacsclient -c --eval "(ediff-directories \"$1\" \"$2\")"
    else
        emacsclient -c --eval "(ediff-files \"$1\" \"$2\")"
    fi
}

#PS1='\[\033[01;32m\]\u@\h \[\033[01;34m\]\w \$ \[\033[00m\]'

case $TERM in
    "dumb")
        export PS1="> "
        ;;
    xterm*|rxvt*|eterm*|screen*)
        export PS1="\[$red\][\! \u@\h \w]$\[$NC\] "
        ;;
    *)
        export PS1="> "
        ;;
esac

unset JAVA_TOOL_OPTIONS

# tailoring 'less'
export PAGER=less
export LESSCHARSET='utf-8'
export LESS=' -M -R '

shopt -s histappend
shopt -s cmdhist
export HISTFILE=$HOME/.bashist/`hostname`.`date +%Y-%m`
touch $HISTFILE && chmod 600 $HISTFILE

# consider for sharing across terminals
#export PROMPT_COMMAND="history -a;history -c;history -r;$PROMPT_COMMAND"
export PROMPT_COMMAND='history -w' #write to history whenever the prompt is displayed
export HISTSIZE=10000 # Long history
export HISTFILESIZE=100000 # Size of historyfile
export HISTCONTROL="ignoreboth" # Ignore duplicates
export HISTIGNORE="&:ls:ll:dir:la:[bf]g:exit"
export HISTTIMEFORMAT='%F_%T '

stty -ixon # disable flow control so C-s search works

pathmunge ${HOME}/usr/bin
pathmunge /usr/local/heroku/bin
pathmunge ${DOTC_DIR}/cask/bin
pathmunge ${HOME}/.cargo/bin # Rust cargo
pathmunge ${HOME}/gocode/bin
pathmunge ${HOME}/.local/bin # python pip packages

export OUTPUT_OPTION=""
export EDITOR=emacsclient

# go
export GOPATH=$HOME/gocode
pathmunge ${GOPATH}/bin

# esp32 dev
if [[ -d "$HOME/.platformio/penv/bin" ]]; then
    pathmunge "$HOME/.platformio/penv/bin"
fi

# rust
if [[ -f "$HOME/.cargo/env" ]]; then
    source "${HOME}/.cargo/env"
fi

# rack sdk development
# see https://vcvrack.com/manual/Building#Building-Rack
if [[ -d "$HOME/sound/Rack-SDK/" ]]; then
    export RACK_DIR=$HOME/sound/Rack-SDK
fi

set -o emacs
shopt -s extglob cdspell checkwinsize cmdhist histverify hostcomplete >& /dev/null

if [[ -f /etc/bash_completion ]]; then
    . /etc/bash_completion
fi

if which keychain > /dev/null; then
    keychain --ignore-missing -Q -q id_rsa
    source ~/.keychain/$HOSTNAME-sh
fi

unset pathmunge
export PATH
xset b off > /dev/null 2>&1

# ln -sfv path/to/private_local_overrides ~/.bashrc.local
if [[ -f "$HOME/.bashrc.local" ]]; then
    source "$HOME/.bashrc.local"
fi

if [[ -f "$HOME/.cargo/env" ]]; then
    source "$HOME/.cargo/env"
fi

source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh
chruby 3.2.2
