#!/usr/bin/ruby
# put this as ~/.irbrc and you shall have commandline completion

IRB.conf[:SAVE_HISTORY] = 1000

require 'irb/completion'
ARGV.concat [ "--readline", "--prompt-mode", "simple" ]

require 'yaml'

def log_stdout(cache: true, ar: true)
  stdout = Logger.new(STDOUT)
  ActiveRecord::Base.logger = stdout if ar
  Rails.cache.logger = stdout if cache
end

def sql(query)
  ActiveRecord::Base.connection.select_all(query)
end
