#!/usr/bin/ruby
# put this as ~/.irbrc and you shall have commandline completion

IRB.conf[:SAVE_HISTORY] = 1000

require 'irb/completion'
ARGV.concat [ "--readline", "--prompt-mode", "simple" ]

require 'yaml'
