#!/usr/bin/ruby
# put this as ~/.irbrc and you shall have commandline completion

IRB.conf[:SAVE_HISTORY] = 1000

require 'irb/completion'
ARGV.concat [ "--readline", "--prompt-mode", "simple" ]

module Kernel
  def m(o)
    ObjectMethods.new(o.public_methods(false).sort)
  end

  class ObjectMethods < Array
    def inspect
      puts self
    end
  end
end


class Object
  def my_methods
    methods - Object.new.methods
  end
end

require 'yaml'
