(source gnu)
(source melpa)
(source org)

(depends-on "haml-mode")
(depends-on "yaml-mode")
(depends-on "sass-mode")
(depends-on "css-mode")
(depends-on "less-css-mode")
(depends-on "markdown-mode")
(depends-on "log4j-mode")
(depends-on "dna-mode")
(depends-on "org-plus-contrib")
(depends-on "graphviz-dot-mode")
(depends-on "web-mode")
(depends-on "epresent")
(depends-on "free-keys")

(depends-on "haskell-mode")
(depends-on "js2-mode")
(depends-on "coffee-mode")
(depends-on "groovy-mode")

;; Elisp
(depends-on "elisp-slime-nav")
(depends-on "flash-region")

;; Clojure
(depends-on "clojure-mode")
(depends-on "clojure-mode-extra-font-locking")
(depends-on "cider")
(depends-on "slamhound")
(depends-on "4clojure")
(depends-on "clojure-cheatsheet")
(depends-on "clj-refactor")

(depends-on "rainbow-delimiters")
(depends-on "color-identifiers-mode")
(depends-on "smartparens")

;; Scheme
(depends-on "geiser")
;; (depends-on "quack")

;; Git
(depends-on "magit")
(depends-on "gist")
(depends-on "github-browse-file")
(depends-on "github-clone")

;; Files and Projects
(depends-on "helm")
(depends-on "flx-ido")
(depends-on "projectile")
(depends-on "helm-projectile")
(depends-on "ag")
(depends-on "wgrep-ag")
(depends-on "smex")
(depends-on "ace-jump-mode")
(depends-on "ace-window")
(depends-on "smartscan")
(depends-on "diminish")

;; Ruby
(depends-on "rbenv")
(depends-on "inf-ruby")
(depends-on "rinari")
(depends-on "bundler")
(depends-on "projectile-rails")
(depends-on "rspec-mode")
(depends-on "feature-mode")
(depends-on "ruby-tools")
(depends-on "robe")
(depends-on "company-inf-ruby")
(depends-on "yari")

(depends-on "starter-kit-eshell")
(depends-on "company")
(depends-on "fuzzy")
(depends-on "expand-region")
(depends-on "multiple-cursors")
(depends-on "occur-context-resize")

(depends-on "yasnippet")
(depends-on "clojure-snippets")

(depends-on "flycheck")
(depends-on "undo-tree")
(depends-on "browse-kill-ring")
(depends-on "evil")

;; Hacking Experiments
(depends-on "simple-httpd")
(depends-on "web-server")

(depends-on "color-theme")
(depends-on "zenburn-theme")
(depends-on "color-theme-solarized")
