(source melpa)
(source org)

(depends-on "haml-mode")
(depends-on "yaml-mode")
(depends-on "sass-mode")
(depends-on "css-mode")
(depends-on "less-css-mode")
(depends-on "markdown-mode")
(depends-on "log4j-mode")
(depends-on "dna-mode")
(depends-on "org-plus-contrib")
(depends-on "graphviz-dot-mode")
(depends-on "web-mode")
(depends-on "epresent")
(depends-on "free-keys")

(depends-on "haskell-mode")
(depends-on "js2-mode")
(depends-on "coffee-mode")
(depends-on "groovy-mode")

;; Elisp
(depends-on "elisp-slime-nav")

;; Clojure
(depends-on "clojure-mode")
(depends-on "clojure-test-mode")
(depends-on "cider")
(depends-on "cider-tracing")
;; (depends-on "nrepl-ritz")
(depends-on "company-cider")
(depends-on "slamhound")
(depends-on "4clojure")
(depends-on "clojure-cheatsheet")

(depends-on "rainbow-delimiters")
(depends-on "color-identifiers-mode")
(depends-on "smartparens")

;; Scheme
(depends-on "geiser")
;; (depends-on "quack")

;; Git
(depends-on "magit")
(depends-on "gist")
(depends-on "github-browse-file")

;; Files and Projects
(depends-on "helm")
(depends-on "find-file-in-project")
(depends-on "flx-ido")
(depends-on "projectile")
(depends-on "helm-projectile")
(depends-on "ag")
(depends-on "ack-and-a-half")
(depends-on "smex")
(depends-on "ace-jump-mode")
(depends-on "smartscan")
(depends-on "diminish")

;; Ruby
(depends-on "rvm")
(depends-on "inf-ruby")
(depends-on "rinari")
(depends-on "bundler")
(depends-on "projectile-rails")
(depends-on "rspec-mode")
(depends-on "ruby-tools")
(depends-on "robe")
(depends-on "company-inf-ruby")
(depends-on "yari")

(depends-on "starter-kit-eshell")
(depends-on "company")
(depends-on "fuzzy")
(depends-on "expand-region")
(depends-on "multiple-cursors")

(depends-on "yasnippet")
(depends-on "angular-snippets")
(depends-on "clojure-snippets")

(depends-on "flycheck")
(depends-on "undo-tree")
(depends-on "evil")

(depends-on "color-theme")
(depends-on "zenburn-theme")
(depends-on "color-theme-solarized")
