(source gnu)
(source melpa)
(source org)
(source "billpiel" "http://billpiel.com/emacs-packages/")

(depends-on "haml-mode")
(depends-on "yaml-mode")
(depends-on "sass-mode")
(depends-on "css-mode")
(depends-on "less-css-mode")
(depends-on "markdown-mode")
;; (depends-on "log4j-mode")
;; (depends-on "dna-mode")
(depends-on "org-plus-contrib")
(depends-on "ob-http")
(depends-on "graphviz-dot-mode")
(depends-on "terraform-mode")
(depends-on "web-mode")
(depends-on "command-log-mode")
(depends-on "epresent")
(depends-on "free-keys")
(depends-on "list-environment")

(depends-on "haskell-mode")
(depends-on "groovy-mode")
(depends-on "gnuplot")
(depends-on "gnuplot-mode")
(depends-on "js2-mode")
(depends-on "coffee-mode")
(depends-on "elm-mode")
(depends-on "lua-mode")
(depends-on "flycheck-elm")
(depends-on "sml-mode")
(depends-on "ob-sml")

;; Elisp
(depends-on "flash-region")
(depends-on "package-lint")

;; Clojure
(depends-on "clojure-mode")
(depends-on "clojure-mode-extra-font-locking")
(depends-on "cider")
(depends-on "cider-decompile")
(depends-on "slamhound")
(depends-on "kibit-helper")
(depends-on "4clojure")
(depends-on "clojure-cheatsheet")
(depends-on "clj-refactor")
(depends-on "flycheck-clojure")
;; (depends-on "sayid")

(depends-on "aggressive-indent")
(depends-on "rainbow-delimiters")
(depends-on "color-identifiers-mode")
(depends-on "smartparens")

;; Erlang/Elixir
(depends-on "erlang")
(depends-on "edts")
(depends-on "elixir-mode")
(depends-on "alchemist")
(depends-on "flycheck-dialyzer")
(depends-on "flycheck-elixir")
(depends-on "ob-elixir")

;; Redis
(depends-on "redis")

;; Scheme
;; (depends-on "geiser")
;; (depends-on "quack")

;; Git
(depends-on "magit")
(depends-on "gitignore-mode")
(depends-on "gitconfig-mode")
(depends-on "ido-completing-read+")
(depends-on "gist")
(depends-on "github-browse-file")
(depends-on "github-clone")

;; Files and Projects
(depends-on "helm")
(depends-on "helm-ag")
(depends-on "helm-unicode")
(depends-on "flx-ido")
(depends-on "projectile")
(depends-on "helm-projectile")
(depends-on "ibuffer-projectile")
(depends-on "ag")
(depends-on "wgrep-ag")
(depends-on "smex")
(depends-on "diminish")

(depends-on "prodigy")

;; Ruby
(depends-on "chruby")
(depends-on "inf-ruby")
(depends-on "rinari")
(depends-on "bundler")
(depends-on "projectile-rails")
(depends-on "rspec-mode")
(depends-on "feature-mode")
(depends-on "ruby-tools")
(depends-on "robe")
(depends-on "company-inf-ruby")
(depends-on "yari")
(depends-on "rubocop")
(depends-on "coverage")

;; Editor
(depends-on "ace-window")
(depends-on "smartscan")
(depends-on "iy-go-to-char")
(depends-on "visual-fill-column")

(depends-on "atomic-chrome")
(depends-on "json-mode")
(depends-on "json-navigator")
;; (depends-on "starter-kit-eshell"
;;             :git "https://github.com/technomancy/emacs-starter-kit"
;;             :branch "v2")

(depends-on "company")
(depends-on "fuzzy")
(depends-on "expand-region")
(depends-on "multiple-cursors")
(depends-on "occur-context-resize")
(depends-on "string-inflection")

(depends-on "yasnippet")
(depends-on "clojure-snippets")

(depends-on "flycheck")
(depends-on "undo-tree")
(depends-on "browse-kill-ring")
(depends-on "evil")

(depends-on "crux")
(depends-on "request")

;; Hacking Experiments
(depends-on "simple-httpd")
(depends-on "web-server")
(depends-on "camcorder")

(depends-on "request")

(depends-on "zenburn-theme")
(depends-on "solarized-theme")
