#!/bin/bash

# grep every revision for a keyword
# Usage: git-grep-history dgtized

# from https://stackoverflow.com/questions/2928584/how-to-grep-search-committed-code-in-the-git-history
git rev-list --all | xargs git grep "$1"
