#!/bin/bash -ex

sudo aptitude install xmonad dmenu

xmonad --recompile

cat <<EOF | sudo tee /usr/share/gnome-session/sessions/xmonad.session
[GNOME Session]
Name=Xmonad Unity
RequiredComponents=gnome-settings-daemon
RequiredProviders=windowmanager;panel
DefaultProvider-windowmanager=xmonad
DefaultProvider-panel=unity-2d-panel
FallbackSession=ubuntu-2d
EOF

cat <<EOF | sudo tee /usr/share/xsessions/xmonad-unity-session.desktop
[Desktop Entry]
Name=XMonad Unity
Comment=Tiling window manager
TryExec=/usr/bin/gnome-session
Exec=gnome-session --session=xmonad
Type=XSession
EOF
