#!/usr/bin/env python

import subprocess
import wnck
import gtk
import time
import sys
import re

name = sys.argv[1]
cmd_name = {
    'emacs': 'emacs',
    'Terminal': 'uxterm',
    'Chrome': 'Chrome'
}[name]

command = {
    'emacs': '/home/clgc/usr/bin/ec -c',
    'Terminal': "/home/clgc/usr/bin/terminal-launch",
    "Chrome": "google-chrome --force-device-scale-factor=1.33"
}[name].split()

screen = wnck.screen_get_default()
while gtk.events_pending():
    gtk.main_iteration()

window_list = screen.get_windows_stacked()

last_active = None
for window in window_list:
    window_name = window.get_application().get_name()
    if window_name == cmd_name or re.search(cmd_name + "$", window_name):
        last_active = window

if last_active:
    timestamp = int(time.time())
    last_active.activate(timestamp)

else:
    subprocess.Popen(command, shell=True)
