#!/usr/bin/env python

import subprocess
import wnck
import gtk
import time
import sys

name = sys.argv[1]
command = {
    'emacs': '/home/clgc/usr/bin/ec -c',
    'Terminal': "gnome-terminal --maximize -e tmux"
}[name].split()

screen = wnck.screen_get_default()
while gtk.events_pending():
    gtk.main_iteration()

window_list = screen.get_windows_stacked()

last_active = None
for window in window_list:
    if window.get_application().get_name() == name:
        last_active = window

if last_active:
    timestamp = int(time.time())
    last_active.activate(timestamp)

else:
    subprocess.Popen(command)
