#!/bin/bash

# http://superuser.com/questions/288320/whats-like-osxs-pbcopy-for-linux
if [ -f /usr/bin/pbcopy ]; then # osx
  cat | /usr/bin/pbcopy
else
  # copy to selection buffer AND clipboard
  cat | xclip -i -sel c -f | xclip -i -sel p
fi
