#!/bin/bash
pushd .
cd ~/install
if wget -N 'ftp://ftp.ruby-lang.org/pub/ruby/stable-snapshot.tar.gz'
then
    echo "Deleting old source"
    rm -rf ruby
    echo "Unpacking..."
    tar zxf stable-snapshot.tar.gz
    cd ruby
    echo "Configuring..."
#    autoconf
    ./configure --prefix=$HOME/usr --with-default-kcode=utf8 --with-readline 
    echo "Compiling..."
    make #>& /dev/null
    echo "Testing..."
    make test 
    echo "Installing.."
    make install >& /dev/null
    echo "Cleaning up..."
    make clean >& /dev/null
    ruby -v
    irb -v 
    ri -v
    cd test
    ruby runner.rb
    echo "Update Complete"
fi
popd

