#!/bin/sh

grepcmd="grep -v '/target/'"

rm -f TAGS
find . -name "*.css" -print > /tmp/tag-list
find . -name "*.html" -print > /tmp/tag-list
find . -name "*.xml" -print > /tmp/tag-list
find . -name "*.gsp" -print >> /tmp/tag-list
find . -name "*.java" -print >> /tmp/tag-list
find . -name "*.groovy" -print >> /tmp/tag-list
find . -name "*.js" -print >> /tmp/tag-list

grep -v target /tmp/tag-list | grep -v '#' | xargs etags --lang=auto -a
